apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "corda-node.fullname" $ }}-config
data:
  ishare.properties: |-
    ishare.EORI=eori
    ishare.key=key
    ishare.cert=cert
    ishare.pass=nvt
    ishare.schemeURL=https://scheme.isharetest.net
    ishare.schemeID=schemeid
    ishare.enabled=false
  {{- if .Values.graphdb.enabled }}
  database.properties: |-
    datafetcher.type=sparql
    graphdb.sparql.url=http://{{ .Release.Name }}-federated-graphdb:7200/repositories/federated
    triplestore.host={{ .Release.Name }}-federated-graphdb
    triplestore.port={{ .Values.graphdb.port }}
    triplestore.private-repository={{ .Values.graphdb.privateRepository }}
    triplestore.repository={{ .Values.graphdb.repository }}
    triplestore.connectTimeoutMillis=10000
    triplestore.socketTimeoutMillis=30000
    triplestore.maxConnectionsPerRoute=50
    triplestore.maxConnectionsTotal=100
    triplestore.protocol=http
  {{ end -}}
  node.conf: |-
    custom = {
      jvmArgs: [ "-Xmx2G" ]
    }
    devMode={{ .Values.devMode }}
    myLegalName="{{ .Values.myLegalName }}"
    {{- if .Values.notary.isNotary  }}
    notary = [validating : {{ .Values.notary.isValidating }}]
    {{- end }}
    p2pAddress={{ printf "%s:%v" .Values.p2pAddress .Values.p2pPort | quote }}
    rpcSettings {
        address={{ printf "%s:%v" .Values.rpc.address .Values.rpcPort | quote }}
        adminAddress={{ printf "%s:%v" .Values.rpc.adminAddress .Values.adminPort | quote }}
    }
    security {
        authService {
            dataSource {
                type={{ .Values.security.datasourceType }}
                users=[
                  {{- range $.Values.security.users }}
                    {
                        password={{ .password }}
                        permissions=[
                            {{- range .permissions }}
                            {{ . }}
                            {{- end }}
                        ]
                        user={{ .user }}
                    }
                  {{- end }}
                ]
            }
        }
    }
    devModeOptions.allowCompatibilityZone={{ .Values.compatibilityZone.enabled }}
    compatibilityZoneURL={{ .Values.compatibilityZone.compatibilityZoneURL | quote }}
 